#!/bin/bash

pandoc $1 -o $(dirname $1)/$(basename $1 .md).pdf --pdf-engine=lualatex \
       -V geometry:margin=1in \
       -V mainfont="Noto Sans" \
       -V monofont="Noto Sans Mono" \
       -V mathfont="Noto Sans Math" \

open $(dirname $1)/$(basename $1 .md).pdf
